### ISSUE TITLE
The Certifier service doesn't work across network

### ISSUE THREAD

**Issue by rgerganov** [vmware-research/certifier-framework-for-confidential-computing#12]
This is how requests are handled in `simpleserver.go`:
```go
        b := make([]byte, 8192)
        n, err := conn.Read(b)
        if err != nil {
                fmt.Printf("n: %d\n", n)
                logEvent("Can't read request", nil, nil)
                return
        }

        request:= &certprotos.TrustRequestMessage{}
        err = proto.Unmarshal(b[0:n], request)
```
The assumption made here is that requests are 8K max and they are entirely read with a single `Read()` call. This is simply wrong. A single `Read()` call may retrieve part of the request and there is no way to know how much is left. As result, `simpleserver` works only on `localhost` and fails with remote clients.
We should either craft a simple protocol (e.g. sending 4 bytes with request size and then sending the request) or use something like gRPC

**Comment by jlmucb** [comment]
This should be fixed now.  Rado: can you check?

**Comment by jlmucb** [comment]
fixed
