### ISSUE TITLE
Setup an authenticated channel with an application outside the security domain 

### ISSUE THREAD

**Issue by arnegoeteyn** [vmware-research/certifier-framework-for-confidential-computing#189]
**Please let me know if this is not the right place for this question**

I am trying to use the certifier framework to do the following:

1. certify a program that is running in the `simulated_enclave`
2. receive the x509 certificate from the certifier server
3. use this certificate to communicate with a server that has nothing to do with the certifier framework but is able to communicate over an SSL connection. In this case the certifier service is a trusted CA on the outside server, such that self signed certificates created by the framework are trusted.

In my attempt to do this I wrote (copy pasted from the internet) a simple Go server that sets up an SSL connection
```go
// https-server.go
package main
import (
	"crypto/tls"
	"log"
	"net/http"
)
var (
        // these are the servers certificates
	CertFilePath = "cert.pem"
	KeyFilePath  = "key.pem"
)
func httpRequestHandler(w http.ResponseWriter, req *http.Request) {
	w.Write([]byte("Hello,World!\n"))
}
func main() {
	// load tls certificates
	serverTLSCert, err := tls.LoadX509KeyPair(CertFilePath, KeyFilePath)
	if err != nil {
		log.Fatalf("Error loading certificate and key file: %v", err)
	}

	tlsConfig := &tls.Config{
		Certificates: []tls.Certificate{serverTLSCert},
	}
	server := http.Server{
		Addr:      ":4443",
		Handler:   http.HandlerFunc(httpRequestHandler),
		TLSConfig: tlsConfig,
	}
	defer server.Close()
	log.Fatal(server.ListenAndServeTLS("", ""))
}
```

I then ran the `example_app.cc` program pointing to the 'outside' server instead of the `example_app` server that is in the security domain. 

I am not sure if I expected it to work but it does not. My outside server prints the following
```
2023/09/01 18:09:43 http: TLS handshake error from 127.0.0.1:37304: local error: tls: bad record MAC
```

Now my actual question: 

Is this something that is possible to achieve with the framework (communicating with the external server over TLS)? Am I misunderstanding something or doing something wrong? 
Any help or pointers would be much appreciated.

Also want to thank you for creating this framework and please let me know if something in my question is not clear!

Have a wonderful day

**Comment by arnegoeteyn** [comment]
When looking a bit deeper to this I suppose this is not working/possible because the confidential application does not accept the the external server's certificate because it's not trusted according to the policy key. 
Is my understanding correct? Would there be a way to achieve something like this? Either by extending the policy key or by allowing the setup of a 'one-way-trusted channel'?

**Comment by jlmucb** [comment]
I'd be interested in the use case since the client will be completely untrusted.  

Having said that, it's possible to do.  We're considering adding a flag to secure_authenticated_channel to specify "server auth only."   In that case, the TLS connection will only authenticate the server (which is common as  in https).  We'll try and decide this quickly and implment it soon if we do.

Thanks for the suggestion.

John

**Comment by arnegoeteyn** [comment]
Closing this since we discussed this in our meeting. We were indeed not looking for a one-way trusted channel
