### ISSUE TITLE
Attestation Report is out of date.

### ISSUE THREAD

**Issue by larrydewey** [vmware-research/certifier-framework-for-confidential-computing#33]
This attestation can be updated to match the current specification. Pulling an attestation report based off of this with the latest firmware will cause fields to be misaligned. 

https://github.com/vmware-research/certifier-framework-for-confidential-computing/blob/e78b65d6153be9251e07ef9f7a1cf5c2b91d9900/src/sev-snp/attestation.h#L54

**Comment by larrydewey** [comment]
I will create a PR from my fork

**Comment by yelvmw** [comment]
I did notice some updates. We pulled the report definition around 2021. Thanks for the reminder!

**Comment by jlmucb** [comment]
Thanks, Larry.  We'll fix all of these.

**Comment by jlmucb** [comment]
updated
