### ISSUE TITLE
Missing X509v3 Extension Verification/Validation

### ISSUE THREAD

**Issue by larrydewey** [vmware-research/certifier-framework-for-confidential-computing#34]
https://github.com/vmware-research/certifier-framework-for-confidential-computing/blob/e78b65d6153be9251e07ef9f7a1cf5c2b91d9900/src/sev-snp/sev_support.cc#L692

While this works to verify the signature, it would also be good to include a function to verify/attest that the [OIDs](https://www.amd.com/system/files/TechDocs/57230.pdf#page=13) provided in the report match the expected values pulled from the VCEK.

**Comment by larrydewey** [comment]
I will create a PR from my fork and submit it for review.

**Comment by yelvmw** [comment]
Draft pull request #152 created.
